language: python
cache: pip
python:
- 3.5
- 3.6
- pypy3.5
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: yozik04
  distributions: sdist
  skip_existing: true
  on:
    tags: true
  password:
    secure: U7SHF0d569qWhWYdL66mPzwy0lLjiRKS8JBCy2QOti8iBEFXkd6pRbRIkO1oifl9E3NS4W+T8vVCNrwtsGrl7W8mR41S6oLaYA8NdBrzAdO6G4zN5rmQFNmnl12dmNQUMirOn9XpaEldUoapKWok4SMhhkw4xsnLcXcdaQrmvUGmBzsRq0tIfZVzvhSXRKr2exegHC5m6Iw5RrLsKE7OdnaBo7kEdWxIhM2Q+g8HuP68Hoj4GYoJ1yxekS4gz+uM+oo74BG9xeRSSqdl0nSlAXt3ENZkcqOQzc3D3pE7ZEcN4YrOGgYfzkZnrB4qG7G2yHkb0j+Q2AJisVIdWRBUSE2kUsxLJgrIH3UhHNNU2MxLsHwVNbSBt3KXQxpnZexwnXm8R1z8po+U/ILzMi3xenTp/8bWKovqWVOx5ctCGvPLctIVMQk9FKNLKIKjaxjWRMv1rq0ioa6WEdh2yJYIG7FndhMzAUACeh17NpbdjTQOLSrefJ14MVbfzwNsbeCRoimVX2EelUN0cWLcesNKgFXNIRb1o2rtsOTsAFTDm819CnTkNuZ5KMY4dLVl/9PQjEJpt8qAxm6gJKb2Ylz8ZReQGnF6SWyLM+gNeYuK1dJxu//Nb+BT/5dCy9nlQB2lI1MIsAe2vyYtqFxmuzCjJnnsJ8KwcytC0KeJr3QI1sQ=
