language: python
cache: pip

python:
  - 3.5
  - 3.6
  - pypy3.5

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest

deploy:
  provider: pypi
  user: yozik04
  distributions: sdist
  on:
    tags: true
  password:
    secure: IXSg5Q83/RT6Rt/2Gn+fvyWNVTP8dFZVdG3Eb0OTul0IDgRfqVrsv+KVVOeJYhKfj0+F/w4G2Up0131G0zIxnZPn3XjJ4EzQd5n+S8eCrEVLkfj+42S5kSxbM25uRkoLmK6zggRKiFGbdz8QH53GHiNU1Z1GNFu2tWEbG7WR9hsyn5ed2rBEnGAfjfV6OJg7+xh6wrTtM+0iDsIgz4pS5mYQLRwauHpVUh0djWLaEkwotTk0APw09mom+ICNwqgabMWCYfRKkyZiGOkU3jVrS7OUH6FZHFER/zVyqebmbahpuRkO73Gc+2VBHugqNuASDi+Dtz6nUSl4G/2je6gOfCCnDAwRjRgMSGxfXYyNcZ9fq+LcIv6G1xBDazSWu1IkfuaroDpHdfEReU9XC41s9q3ck/yLfyegYIyrDv1UyqomOGrdSVE9Yym3KeSidqBA1MgwY0nkPckvV8fm1aDoRYuChE2aTBtyZqhOhd6XNaqq7BCV+9OgitpDoFWQQ/1frs5LWW7pxRBChhpOwXQoukcSdDfgq4wGFMruLMKuMoFYSNAB+Lodkps+7zs8GjErCRF+Pt6orWngGemeKlZLN2h4kb14DJpGFg4+aFPEs9F9zYbV0SBILRMlKiF6UR9/t0DROnNByvv2Xsq8dsdhhEelK2goZmfKXUhu+6XrhgU=